import type { Listing } from "@/lib/listings/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    slug: "quill-ai",
    brandName: "Quill",
    title: "Quill AI",
    description: "Draft, edit, and repurpose long-form writing with an AI copilot trained on your voice.",
    deliverables: ["IG Reel · 3mo", "TikTok · 1mo"],
    retailValue: 180,
    months: 3,
    slotsRemaining: 4,
    totalSlots: 10,
    category: "AI Tools",
    platform: "Instagram",
  },
  {
    slug: "framecraft",
    brandName: "Framecraft",
    title: "Framecraft Pro",
    description: "Build and maintain design systems with live component sync across Figma and code.",
    deliverables: ["YouTube review · 6mo"],
    retailValue: 288,
    months: 6,
    slotsRemaining: 2,
    totalSlots: 12,
    category: "Design",
    platform: "YouTube",
    saved: true,
  },
  {
    slug: "loopmail",
    brandName: "Loopmail",
    title: "Loopmail Growth",
    description: "Automated email flows and audience segmentation for creators launching a product.",
    deliverables: ["X thread · 1mo"],
    retailValue: 96,
    months: 3,
    slotsRemaining: 0,
    totalSlots: 8,
    category: "Marketing",
    platform: "X",
  },
  {
    slug: "codeharbor",
    brandName: "Codeharbor",
    title: "Codeharbor Pro",
    description: "A full cloud dev environment with instant previews and one-click deploys.",
    deliverables: ["YouTube review · 3mo", "TikTok · 3mo"],
    retailValue: 348,
    months: 12,
    slotsRemaining: 5,
    totalSlots: 15,
    category: "Dev Tools",
    platform: "YouTube",
  },
  {
    slug: "tasknest",
    brandName: "Tasknest",
    title: "Tasknest Team",
    description: "Lightweight project planning built for small creative teams and solo founders.",
    deliverables: ["IG Reel · 3mo"],
    retailValue: 120,
    months: 3,
    slotsRemaining: 3,
    totalSlots: 10,
    category: "Productivity",
    platform: "Instagram",
  },
  {
    slug: "pixelforge",
    brandName: "Pixelforge",
    title: "Pixelforge Studio",
    description: "Generate on-brand social assets in seconds from a single style reference.",
    deliverables: ["IG carousel · 6mo", "TikTok · 1mo"],
    retailValue: 216,
    months: 6,
    slotsRemaining: 0,
    totalSlots: 12,
    category: "Design",
    platform: "Instagram",
  },
  {
    slug: "sparkcopy",
    brandName: "Sparkcopy",
    title: "Sparkcopy Pro",
    description: "Turn a rough brief into ad copy, captions, and landing page sections in one pass.",
    deliverables: ["TikTok · 3mo"],
    retailValue: 150,
    months: 3,
    slotsRemaining: 6,
    totalSlots: 20,
    category: "AI Tools",
    platform: "TikTok",
    saved: true,
  },
  {
    slug: "adreach",
    brandName: "Adreach",
    title: "Adreach Growth",
    description: "Plan, launch, and report on paid campaigns across every major ad platform.",
    deliverables: ["X thread · 1mo", "IG Reel · 3mo"],
    retailValue: 264,
    months: 3,
    slotsRemaining: 1,
    totalSlots: 10,
    category: "Marketing",
    platform: "X",
  },
  {
    slug: "shipdesk",
    brandName: "Shipdesk",
    title: "Shipdesk Pro",
    description: "Ship changelogs, track releases, and notify users automatically from one dashboard.",
    deliverables: ["YouTube review · 6mo"],
    retailValue: 204,
    months: 6,
    slotsRemaining: 2,
    totalSlots: 10,
    category: "Dev Tools",
    platform: "YouTube",
    saved: true,
  },
];
