import type { Listing } from "@/lib/listings/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    slug: "paper",
    brandName: "Paper",
    websiteUrl: "https://paper.design",
    title: "Paper Pro",
    description: "An AI-native design canvas where what you draw is real HTML and CSS, not a proprietary file format.",
    deliverables: ["IG carousel · 3mo"],
    retailValue: 48,
    months: 3,
    slotsRemaining: 5,
    totalSlots: 12,
    category: "Design",
    platform: "Instagram",
  },
  {
    slug: "cursor",
    brandName: "Cursor",
    websiteUrl: "https://cursor.com",
    title: "Cursor Pro",
    description: "The AI code editor built on VS Code, with a model that reads your whole codebase as you write.",
    deliverables: ["YouTube review · 6mo"],
    retailValue: 120,
    months: 6,
    slotsRemaining: 3,
    totalSlots: 10,
    category: "Dev Tools",
    platform: "YouTube",
    saved: true,
  },
  {
    slug: "dia-browser",
    brandName: "Dia",
    websiteUrl: "https://diabrowser.com",
    title: "Dia Browser",
    description: "A browser built around an AI chat that reads your open tabs, drafts replies, and remembers context as you work.",
    deliverables: ["TikTok · 3mo"],
    retailValue: 60,
    months: 3,
    slotsRemaining: 4,
    totalSlots: 10,
    category: "AI Tools",
    platform: "TikTok",
  },
  {
    slug: "notion",
    brandName: "Notion",
    websiteUrl: "https://notion.com",
    title: "Notion Plus",
    description: "Docs, wikis, and project tracking in one connected workspace, with AI built into every page.",
    deliverables: ["X thread · 1mo", "IG Reel · 3mo"],
    retailValue: 120,
    months: 12,
    slotsRemaining: 6,
    totalSlots: 15,
    category: "Productivity",
    platform: "X",
  },
  {
    slug: "youtube-premium",
    brandName: "YouTube",
    websiteUrl: "https://www.youtube.com/premium",
    title: "YouTube Premium",
    description: "Ad-free video across YouTube and YouTube Music, with background play and offline downloads.",
    deliverables: ["YouTube review · 3mo"],
    retailValue: 48,
    months: 3,
    slotsRemaining: 5,
    totalSlots: 12,
    category: "Productivity",
    platform: "YouTube",
  },
  {
    slug: "apple-music",
    brandName: "Apple Music",
    websiteUrl: "https://music.apple.com",
    title: "Apple Music",
    description: "Ad-free streaming with lossless and spatial audio across more than 100 million songs.",
    deliverables: ["TikTok · 3mo"],
    retailValue: 36,
    months: 3,
    slotsRemaining: 7,
    totalSlots: 15,
    category: "Productivity",
    platform: "TikTok",
  },
  {
    slug: "elevenlabs",
    brandName: "ElevenLabs",
    websiteUrl: "https://elevenlabs.io",
    title: "ElevenLabs Creator",
    description: "Generate lifelike voiceovers and clone your own voice with the AI audio platform built for creators.",
    deliverables: ["YouTube review · 3mo"],
    retailValue: 66,
    months: 3,
    slotsRemaining: 4,
    totalSlots: 10,
    category: "AI Tools",
    platform: "YouTube",
  },
  {
    slug: "higgsfield",
    brandName: "Higgsfield",
    websiteUrl: "https://higgsfield.ai",
    title: "Higgsfield Starter",
    description: "Turn a prompt into cinematic AI video, with motion presets, camera control, and consistent characters.",
    deliverables: ["TikTok · 3mo"],
    retailValue: 57,
    months: 3,
    slotsRemaining: 6,
    totalSlots: 12,
    category: "AI Tools",
    platform: "TikTok",
  },
  {
    slug: "procreate",
    brandName: "Procreate",
    websiteUrl: "https://procreate.com",
    title: "Procreate",
    description: "The industry-standard iPad illustration app, with a full brush engine and animation tools in one lifetime license.",
    deliverables: ["IG carousel · 1mo"],
    retailValue: 13,
    months: 1,
    slotsRemaining: 8,
    totalSlots: 15,
    category: "Design",
    platform: "Instagram",
  },
  {
    slug: "canva",
    brandName: "Canva",
    websiteUrl: "https://canva.com",
    title: "Canva Pro",
    description: "Design anything from social posts to presentations, with a huge template library and one-click brand kits.",
    deliverables: ["TikTok · 3mo"],
    retailValue: 54,
    months: 3,
    slotsRemaining: 9,
    totalSlots: 20,
    category: "Design",
    platform: "TikTok",
  },
  {
    slug: "spotify",
    brandName: "Spotify",
    websiteUrl: "https://spotify.com",
    title: "Spotify Premium",
    description: "Ad-free music streaming with offline downloads and unlimited skips across every playlist.",
    deliverables: ["TikTok · 3mo"],
    retailValue: 39,
    months: 3,
    slotsRemaining: 6,
    totalSlots: 15,
    category: "Productivity",
    platform: "TikTok",
  },
];
