"use client";

import Image from "next/image";
import Link from "next/link";
import { CheckIcon, ShieldCheckIcon } from "@heroicons/react/24/outline";
import { useState } from "react";
import { CART_ITEMS } from "@/lib/mock-creator";
import Button from "@/components/atoms/Button/Button";
import { CreatorBreadcrumb } from "@/components/molecules/CreatorBreadcrumb";
import { CreatorShell } from "@/components/templates/CreatorShell";

export default function CheckoutPage() {
  const [confirmed, setConfirmed] = useState(false);
  const total = CART_ITEMS.reduce((sum, item) => sum + item.value, 0);
  return <CreatorShell><div className="mx-auto max-w-3xl px-5 py-8 sm:px-8 sm:py-14">{confirmed ? <div className="mx-auto max-w-xl rounded-[2rem] border border-neutral-200 bg-white p-8 text-center shadow-[0_15px_60px_rgba(0,0,0,0.05)] sm:p-12"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#A3FF38] text-neutral-950"><CheckIcon className="size-8 stroke-[3]" /></div><p className="mt-7 text-xs font-bold tracking-[0.15em] text-[#73b61f] uppercase">Receipt created</p><h1 className="mt-2 text-3xl font-bold tracking-tight">You’ve shopped {CART_ITEMS.length} products.</h1><p className="mt-4 text-sm leading-7 text-neutral-500">Brands will review your profile and get back to you. Your shops are now waiting in one place.</p><Link href="/shops" className="mt-8 inline-block"><Button size="lg">Go to My Shops</Button></Link></div> : <><CreatorBreadcrumb items={[{ label: "Shop", href: "/explore" }, { label: "Cart", href: "/cart" }, { label: "Checkout" }]} /><header className="mt-7"><p className="text-xs font-bold tracking-[0.15em] text-[#73b61f] uppercase">One last look</p><h1 className="mt-1 text-4xl font-bold tracking-tight">Confirm your shop</h1><p className="mt-2 text-sm text-neutral-500">No payment details. Your profile is your pitch.</p></header><div className="mt-9 overflow-hidden rounded-[1.75rem] border border-neutral-200 bg-white">{CART_ITEMS.map(item => <div key={item.id} className="flex items-center gap-4 border-b border-neutral-100 p-5 last:border-0"><div className="grid size-12 place-items-center rounded-xl bg-neutral-50"><Image src={item.logo} alt="" width={26} height={26} className="size-7 object-contain" /></div><div className="min-w-0 flex-1"><p className="text-xs text-neutral-500">{item.brand}</p><p className="font-bold">{item.product}</p><p className="mt-0.5 text-xs text-neutral-500">{item.tier} · {item.access} access</p></div><p className="font-bold">${item.value}</p></div>)}<div className="bg-[#efffdc] p-5"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-[#477a0b]">Total retail value</p><p className="mt-0.5 text-xs text-[#477a0b]/70">Paid with your chosen content</p></div><p className="text-3xl font-bold tracking-tight">${total}</p></div></div></div><div className="mt-7 flex items-start gap-3 rounded-2xl border border-neutral-200 bg-white p-4"><ShieldCheckIcon className="mt-0.5 size-5 shrink-0 text-[#73b61f]" /><p className="text-sm leading-6 text-neutral-600">By confirming, you’re asking each brand to review your public profile. Approved shops give you a delivery deadline and unlock access once your proof is confirmed.</p></div><Button onClick={() => setConfirmed(true)} size="lg" fullWidth className="mt-7">Confirm {CART_ITEMS.length} shops</Button></>}</div></CreatorShell>;
}
